export default {
    FETCH_AIRPORTS: 'FETCH_AIRPORTS',
    FETCH_AIRPORTS_SUCCESS: 'FETCH_AIRPORTS_SUCCESS',
    FETCH_AIRPORTS_ERROR: 'FETCH_AIRPORTS_ERROR',
    CHOOSE_AIRPORT: 'CHOOSE_AIRPORT',
    FETCH_TICKETS: 'FETCH_TICKETS',
    FETCH_TICKETS_SUCCESS: 'FETCH_TICKETS_SUCCESS',
    FETCH_TICKETS_ERROR: 'FETCH_TICKETS_ERROR'
};